import Head from "next/head";
import Link from "next/link";
import dynamic from "next/dynamic";
import { useEffect, useState } from "react";
import ResearchNavbar from "../../components/Layout/ResearchNavbar";
import styles from "../../styles/Research.module.css";

const MetricChart = dynamic(() => import("../../components/Research/MetricChart"), { ssr: false });
const stageLabel = { story: "故事阶段", evidence: "证据形成", consensus: "共识完成" };
const chain = [{id:"usage",label:"场景 / 使用",question:"用户是否持续使用？"},{id:"revenue",label:"收入",question:"使用能否稳定收费？"},{id:"profit",label:"利润",question:"单位经济是否改善？"},{id:"cashflow",label:"现金流",question:"利润能否转成现金？"},{id:"shareholder",label:"股东价值",question:"价值是否归属于每股？"}];
const tabs = [{id:"overview",label:"总览"},{id:"evidence",label:"证据链"},{id:"metrics",label:"指标趋势"},{id:"events",label:"事件"},{id:"review",label:"日志与复盘"}];

function Field({ label, children }) { return <label>{label}{children}</label>; }
function Modal({ title, eyebrow, onClose, children }) { return <div className={styles.modalBackdrop} onMouseDown={onClose}><div className={styles.modal} onMouseDown={e=>e.stopPropagation()}><div><span className={styles.eyebrow}>{eyebrow}</span><h2>{title}</h2></div>{children}</div></div>; }

export default function AssetResearch() {
  const [bundle, setBundle] = useState(null); const [tab, setTab] = useState("overview"); const [modal, setModal] = useState(null); const [darkMode, setDarkMode] = useState(() => typeof window !== "undefined" && localStorage.getItem("portfolio-theme") === "dark");
  const [form, setForm] = useState({});
  useEffect(() => { const id = location.pathname.split("/").pop(); const dark = localStorage.getItem("portfolio-theme") === "dark"; document.documentElement.dataset.theme=dark?"dark":"light"; fetch(`/api/research?assetId=${id}`).then(r=>r.ok?r.json():Promise.reject()).then(setBundle).catch(()=>setBundle({error:true})); }, []);
  const toggleTheme=()=>setDarkMode(c=>{const n=!c;localStorage.setItem("portfolio-theme",n?"dark":"light");document.documentElement.dataset.theme=n?"dark":"light";return n;});
  const open=(name, defaults={})=>{setForm(defaults);setModal(name);};
  async function add(type, data) { const response=await fetch("/api/research",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type,data:{...data,assetId:bundle.asset.id}})}); const item=await response.json(); setBundle(current=>({...current,[type]:[...current[type],item]})); setModal(null); }
  async function update(type, id, data) { const response=await fetch("/api/research",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({type,id,data})}); const item=await response.json(); if(type==="assets")setBundle(current=>({...current,asset:item}));else setBundle(current=>({...current,[type]:current[type].map(entry=>entry.id===id?item:entry)})); }
  async function editAsset() { const thesis=prompt("核心研究逻辑",bundle.asset.thesis); if(thesis===null)return; const conclusion=prompt("当前观察结论",bundle.asset.conclusion||""); if(conclusion===null)return; await update("assets",bundle.asset.id,{thesis,conclusion}); }
  async function editHypothesis(item) { const title=prompt("假设标题",item.title); if(title===null)return; const description=prompt("可验证描述",item.description); if(description===null)return; const confidence=Number(prompt("置信度 0-100",item.confidence)); await update("hypotheses",item.id,{title,description,confidence:Number.isFinite(confidence)?Math.max(0,Math.min(100,confidence)):item.confidence}); }
  async function editQuestion(item) { const text=prompt("未决问题",item.text); if(text===null)return; const priority=prompt("优先级 high / medium / low",item.priority); if(priority===null)return; await update("questions",item.id,{text,priority:["high","medium","low"].includes(priority)?priority:item.priority}); }
  async function setStage(next) { const old=bundle.asset.stage; if(old===next)return; const reason=prompt("记录阶段变化依据："); if(!reason)return; const response=await fetch("/api/research",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"assets",id:bundle.asset.id,data:{stage:next}})}); const asset=await response.json(); const stageResponse=await fetch("/api/research",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"stageChanges",data:{assetId:asset.id,fromStage:old,toStage:next,date:new Date().toISOString().slice(0,10),reason,evidenceIds:[]}})}); const change=await stageResponse.json(); setBundle(c=>({...c,asset,stageChanges:[...c.stageChanges,change]})); }
  if (!bundle) return <div className={styles.loading}>Loading asset research…</div>; if(bundle.error)return <div className={styles.loading}>Asset not found. <Link href="/research">返回监控列表</Link></div>;
  const {asset}=bundle; const verified=bundle.evidence.filter(e=>e.verification==="verified").length; const latestJournal=[...bundle.journal].sort((a,b)=>b.date.localeCompare(a.date))[0];
  const exportData=()=>{const blob=new Blob([JSON.stringify(bundle,null,2)],{type:"application/json"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`${asset.symbol}-research.json`;link.click();URL.revokeObjectURL(link.href)};

  return <><Head><title>{asset.symbol} Research | TMs Portfolio</title></Head><ResearchNavbar darkMode={darkMode} onTheme={toggleTheme} onExport={exportData}/><main className={styles.page}>
    <div className={styles.breadcrumb}><Link href="/research">Research monitor</Link><span>/</span><b>{asset.symbol}</b></div>
    <section className={styles.assetHero}><div className={styles.tickerMark}>{asset.symbol.slice(0,2)}</div><div className={styles.assetTitle}><div><span>{asset.assetType} · {asset.market}</span><i className={`${styles.stagePill} ${styles[asset.stage]}`}>{stageLabel[asset.stage]}</i></div><h1>{asset.symbol} <small>{asset.name}</small></h1><p>{asset.thesis}</p></div><div className={styles.heroActions}><button onClick={editAsset}>编辑标的</button><select value={asset.stage} onChange={e=>setStage(e.target.value)} aria-label="研究阶段"><option value="story">故事阶段</option><option value="evidence">证据形成</option><option value="consensus">共识完成</option></select><button className={styles.primaryButton} onClick={()=>open("evidence",{chainStage:"usage",direction:"support",strength:3,verification:"partial",observedAt:new Date().toISOString().slice(0,10)})}>＋ 添加证据</button></div></section>
    <nav className={styles.detailTabs}>{tabs.map(t=><button key={t.id} onClick={()=>setTab(t.id)} className={tab===t.id?styles.tabActive:""}>{t.label}<span>{t.id==="evidence"?bundle.evidence.length:t.id==="metrics"?bundle.metrics.length:t.id==="events"?bundle.events.length:""}</span></button>)}</nav>

    {tab==="overview"&&<div className={styles.detailGrid}><section className={styles.mainColumn}>
      <div className={styles.sectionHeader}><div><span className={styles.eyebrow}>RESEARCH STATE</span><h2>证据形成概览</h2></div><button onClick={()=>setTab("evidence")}>查看完整证据链 →</button></div>
      <div className={styles.chainStrip}>{chain.map((c,index)=>{const ev=bundle.evidence.filter(e=>e.chainStage===c.id);return <div key={c.id} className={ev.length?styles.chainActive:""}><span>{String(index+1).padStart(2,"0")}</span><b>{c.label}</b><small>{ev.length} 条证据</small>{index<chain.length-1&&<i>→</i>}</div>})}</div>
      <div className={styles.panel}><div className={styles.sectionHeader}><div><span className={styles.eyebrow}>HYPOTHESES</span><h2>研究假设</h2></div><button onClick={()=>open("hypothesis",{status:"testing",confidence:50})}>＋ 新增</button></div>{bundle.hypotheses.map(h=><article className={styles.hypothesis} key={h.id}><div><i className={styles[h.status]}/><div><b>{h.title}</b><p>{h.description}</p></div></div><span><em>{h.confidence}%</em><small>置信度</small><button className={styles.inlineEdit} onClick={()=>editHypothesis(h)}>编辑</button></span></article>)}</div>
      <div className={styles.panel}><div className={styles.sectionHeader}><div><span className={styles.eyebrow}>LATEST EVIDENCE</span><h2>最近证据</h2></div><button onClick={()=>setTab("evidence")}>全部记录</button></div>{[...bundle.evidence].sort((a,b)=>b.observedAt.localeCompare(a.observedAt)).slice(0,4).map(e=><EvidenceRow key={e.id} evidence={e}/>)}</div>
    </section><aside className={styles.rightColumn}>
      <div className={styles.signalCard}><span className={styles.eyebrow}>CURRENT CONCLUSION</span><h3>{asset.conclusion}</h3><div><span><b>{verified}/{bundle.evidence.length}</b><small>证据已验证</small></span><span><b>{bundle.questions.filter(q=>q.status==="open").length}</b><small>未决问题</small></span></div></div>
      <div className={styles.panel}><div className={styles.sectionHeader}><h3>关键指标</h3><button onClick={()=>setTab("metrics")}>趋势 →</button></div>{bundle.metrics.map(m=>{const values=bundle.metricValues.filter(v=>v.metricId===m.id).sort((a,b)=>a.date.localeCompare(b.date));const value=values.at(-1);return <div className={styles.metricMini} key={m.id}><span><b>{m.name}</b><small>{m.frequency}</small></span><em>{value?.value??"--"}<small> {m.unit}</small></em></div>})}</div>
      <div className={styles.panel}><div className={styles.sectionHeader}><h3>未决问题</h3><button onClick={()=>open("question",{priority:"medium",status:"open"})}>＋</button></div>{bundle.questions.filter(q=>q.status==="open").map(q=><div className={styles.question} key={q.id}><i className={styles[q.priority]}/><p>{q.text}</p><button className={styles.inlineEdit} onClick={()=>editQuestion(q)}>编辑</button></div>)}</div>
      {latestJournal&&<div className={styles.quoteCard}><span>{latestJournal.date} · {latestJournal.entryType}</span><p>“{latestJournal.body}”</p><small>置信度 {latestJournal.confidenceBefore} → {latestJournal.confidenceAfter}</small></div>}
    </aside></div>}

    {tab==="evidence"&&<section className={styles.fullSection}><div className={styles.sectionHeader}><div><span className={styles.eyebrow}>EVIDENCE CHAIN</span><h2>从真实使用到每股价值</h2><p>证据必须跨越整条经济链，而不是停留在合作与叙事。</p></div><button className={styles.primaryButton} onClick={()=>open("evidence",{chainStage:"usage",direction:"support",strength:3,verification:"partial",observedAt:new Date().toISOString().slice(0,10)})}>＋ 添加证据</button></div><div className={styles.evidenceBoard}>{chain.map((c,index)=><div className={styles.chainColumn} key={c.id}><header><span>{String(index+1).padStart(2,"0")}</span><div><b>{c.label}</b><small>{c.question}</small></div></header>{bundle.evidence.filter(e=>e.chainStage===c.id).map(e=><EvidenceCard evidence={e} key={e.id}/>)}<button onClick={()=>open("evidence",{chainStage:c.id,direction:"support",strength:3,verification:"partial",observedAt:new Date().toISOString().slice(0,10)})}>＋ 记录本环节证据</button></div>)}</div></section>}

    {tab==="metrics"&&<section className={styles.fullSection}><div className={styles.sectionHeader}><div><span className={styles.eyebrow}>LEADING & RESULT METRICS</span><h2>指标趋势</h2><p>为每个指标定义目标、频率与方向，避免事后挑选数据。</p></div><button className={styles.primaryButton} onClick={()=>open("metric",{frequency:"quarterly",direction:"up"})}>＋ 新建指标</button></div><div className={styles.metricGrid}>{bundle.metrics.map(m=><div className={styles.chartPanel} key={m.id}><div><span><b>{m.name}</b><small>{m.description}</small></span><em>目标 {m.target} {m.unit}</em></div><MetricChart metric={m} values={bundle.metricValues.filter(v=>v.metricId===m.id)} darkMode={darkMode}/><button onClick={()=>open("value",{metricId:m.id,date:new Date().toISOString().slice(0,10)})}>＋ 记录新数值</button></div>)}</div></section>}

    {tab==="events"&&<section className={styles.fullSection}><div className={styles.sectionHeader}><div><span className={styles.eyebrow}>EVENT LOG</span><h2>事件与信息源</h2><p>把财报、公告、新闻和手工观察关联到研究链路。</p></div><button className={styles.primaryButton} onClick={()=>open("event",{eventType:"news",date:new Date().toISOString().slice(0,10)})}>＋ 记录事件</button></div><div className={styles.timeline}>{[...bundle.events].sort((a,b)=>b.date.localeCompare(a.date)).map(e=><article key={e.id}><time>{e.date}</time><div><span>{e.eventType}</span><h3>{e.title}</h3><p>{e.summary}</p><small>{(e.chainStages||[]).map(s=>chain.find(c=>c.id===s)?.label).filter(Boolean).join(" · ")}</small>{e.sourceUrl&&<a href={e.sourceUrl} target="_blank" rel="noreferrer">打开来源 ↗</a>}</div></article>)}</div></section>}

    {tab==="review"&&<section className={styles.fullSection}><div className={styles.sectionHeader}><div><span className={styles.eyebrow}>DECISIONS & REVIEW</span><h2>判断、行动与复盘</h2><p>保留当时知道什么、为何改变，以及结果与过程是否一致。</p></div><div><button onClick={()=>open("action",{actionType:"watch",date:new Date().toISOString().slice(0,10),positionSize:0})}>记录行动</button><button className={styles.primaryButton} onClick={()=>open("journal",{entryType:"judgement",date:new Date().toISOString().slice(0,10),confidenceBefore:50,confidenceAfter:50})}>＋ 写观察日志</button></div></div><div className={styles.reviewGrid}><div className={styles.panel}><h3>观察日志</h3>{[...bundle.journal].sort((a,b)=>b.date.localeCompare(a.date)).map(j=><article className={styles.journal} key={j.id}><time>{j.date}</time><div><span>{j.entryType}</span><h3>{j.title}</h3><p>{j.body}</p><small>置信度 {j.confidenceBefore} → {j.confidenceAfter}</small></div></article>)}</div><div><div className={styles.panel}><h3>阶段变化</h3>{[...bundle.stageChanges].reverse().map(s=><div className={styles.stageChange} key={s.id}><time>{s.date}</time><p><b>{stageLabel[s.fromStage]}</b> → <b>{stageLabel[s.toStage]}</b></p><small>{s.reason}</small></div>)}</div><div className={styles.panel}><h3>仓位 / 行动</h3>{[...bundle.actions].reverse().map(a=><div className={styles.actionRow} key={a.id}><span><b>{a.actionType}</b><small>{a.date}</small></span><em>{a.positionSize}%</em><p>{a.reason}</p></div>)}</div></div></div></section>}
  </main>{modal&&<EntryModal type={modal} form={form} setForm={setForm} bundle={bundle} onClose={()=>setModal(null)} onSubmit={add}/>}</>;
}

function EvidenceRow({evidence:e}) { return <article className={styles.evidenceRow}><span className={`${styles.directionDot} ${styles[e.direction]}`}/><div><b>{e.title}</b><p>{e.detail}</p><small>{e.observedAt} · {e.sourceName}</small></div><span className={styles.strength}>{Array.from({length:5},(_,i)=><i key={i} className={i<e.strength?styles.filled:""}/>)}</span></article>; }
function EvidenceCard({evidence:e}) { return <article className={styles.evidenceCard}><div><span className={`${styles.directionTag} ${styles[e.direction]}`}>{e.direction}</span><span>{e.verification}</span></div><h3>{e.title}</h3><p>{e.detail}</p><footer><span>{e.observedAt}</span><b>{e.sourceName}</b></footer></article>; }

function EntryModal({type,form,setForm,bundle,onClose,onSubmit}) {
  const update=(key,value)=>setForm({...form,[key]:value}); const submit=(e)=>{e.preventDefault();const map={evidence:"evidence",hypothesis:"hypotheses",question:"questions",metric:"metrics",value:"metricValues",event:"events",journal:"journal",action:"actions"};let data={...form};if(type==="event")data={...data,chainStages:String(data.chainStages||"").split(",").map(v=>v.trim()).filter(Boolean),hypothesisIds:data.hypothesisId?[data.hypothesisId]:[]};onSubmit(map[type],data)};
  const titles={evidence:"记录新证据",hypothesis:"新增研究假设",question:"新增未决问题",metric:"定义关键指标",value:"记录指标数值",event:"记录研究事件",journal:"写观察日志",action:"记录仓位或行动"};
  return <Modal title={titles[type]} eyebrow="STRUCTURED RESEARCH ENTRY" onClose={onClose}><form onSubmit={submit}>
    {type==="evidence"&&<><Field label="证据链环节"><select value={form.chainStage} onChange={e=>update("chainStage",e.target.value)}>{chain.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></Field><Field label="标题"><input required value={form.title||""} onChange={e=>update("title",e.target.value)}/></Field><Field label="观察详情"><textarea required rows="4" value={form.detail||""} onChange={e=>update("detail",e.target.value)}/></Field><div className={styles.formGrid}><Field label="方向"><select value={form.direction} onChange={e=>update("direction",e.target.value)}><option value="support">支持</option><option value="neutral">中性</option><option value="risk">风险</option></select></Field><Field label="强度 1-5"><input type="number" min="1" max="5" value={form.strength} onChange={e=>update("strength",Number(e.target.value))}/></Field></div><div className={styles.formGrid}><Field label="验证状态"><select value={form.verification} onChange={e=>update("verification",e.target.value)}><option value="unverified">未验证</option><option value="partial">部分验证</option><option value="verified">已验证</option></select></Field><Field label="观察日期"><input type="date" value={form.observedAt} onChange={e=>update("observedAt",e.target.value)}/></Field></div><Field label="来源名称"><input required value={form.sourceName||""} onChange={e=>update("sourceName",e.target.value)}/></Field><Field label="来源 URL"><input type="url" value={form.sourceUrl||""} onChange={e=>update("sourceUrl",e.target.value)}/></Field><Field label="关联假设"><select value={form.hypothesisId||""} onChange={e=>update("hypothesisId",e.target.value)}><option value="">无</option>{bundle.hypotheses.map(h=><option value={h.id} key={h.id}>{h.title}</option>)}</select></Field></>}
    {type==="hypothesis"&&<><Field label="假设标题"><input required value={form.title||""} onChange={e=>update("title",e.target.value)}/></Field><Field label="可验证描述"><textarea required rows="4" value={form.description||""} onChange={e=>update("description",e.target.value)}/></Field><div className={styles.formGrid}><Field label="状态"><select value={form.status} onChange={e=>update("status",e.target.value)}><option value="testing">验证中</option><option value="confirmed">已确认</option><option value="rejected">已证伪</option></select></Field><Field label="置信度"><input type="number" min="0" max="100" value={form.confidence} onChange={e=>update("confidence",Number(e.target.value))}/></Field></div></>}
    {type==="question"&&<><Field label="未决问题"><textarea required rows="4" value={form.text||""} onChange={e=>update("text",e.target.value)}/></Field><Field label="优先级"><select value={form.priority} onChange={e=>update("priority",e.target.value)}><option value="high">高</option><option value="medium">中</option><option value="low">低</option></select></Field></>}
    {type==="metric"&&<><Field label="指标名称"><input required value={form.name||""} onChange={e=>update("name",e.target.value)}/></Field><div className={styles.formGrid}><Field label="单位"><input required value={form.unit||""} onChange={e=>update("unit",e.target.value)}/></Field><Field label="目标值"><input type="number" step="any" required value={form.target||""} onChange={e=>update("target",Number(e.target.value))}/></Field></div><div className={styles.formGrid}><Field label="观察频率"><select value={form.frequency} onChange={e=>update("frequency",e.target.value)}><option value="weekly">每周</option><option value="monthly">每月</option><option value="quarterly">每季</option><option value="annual">每年</option></select></Field><Field label="期望方向"><select value={form.direction} onChange={e=>update("direction",e.target.value)}><option value="up">上升</option><option value="down">下降</option><option value="stable">稳定</option></select></Field></div><Field label="指标意义"><textarea rows="3" value={form.description||""} onChange={e=>update("description",e.target.value)}/></Field></>}
    {type==="value"&&<><Field label="指标"><select value={form.metricId} onChange={e=>update("metricId",e.target.value)}>{bundle.metrics.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></Field><div className={styles.formGrid}><Field label="日期"><input type="date" required value={form.date} onChange={e=>update("date",e.target.value)}/></Field><Field label="数值"><input type="number" step="any" required value={form.value||""} onChange={e=>update("value",Number(e.target.value))}/></Field></div><Field label="备注"><input value={form.note||""} onChange={e=>update("note",e.target.value)}/></Field></>}
    {type==="event"&&<><div className={styles.formGrid}><Field label="事件类型"><select value={form.eventType} onChange={e=>update("eventType",e.target.value)}><option value="earnings">财报</option><option value="announcement">公告</option><option value="news">新闻</option><option value="observation">手工观察</option></select></Field><Field label="日期"><input type="date" value={form.date} onChange={e=>update("date",e.target.value)}/></Field></div><Field label="事件标题"><input required value={form.title||""} onChange={e=>update("title",e.target.value)}/></Field><Field label="摘要"><textarea required rows="4" value={form.summary||""} onChange={e=>update("summary",e.target.value)}/></Field><Field label="关联链路（逗号分隔：usage,revenue,profit,cashflow,shareholder）"><input value={form.chainStages||""} onChange={e=>update("chainStages",e.target.value)}/></Field><Field label="来源 URL"><input type="url" value={form.sourceUrl||""} onChange={e=>update("sourceUrl",e.target.value)}/></Field><Field label="关联假设"><select value={form.hypothesisId||""} onChange={e=>update("hypothesisId",e.target.value)}><option value="">无</option>{bundle.hypotheses.map(h=><option value={h.id} key={h.id}>{h.title}</option>)}</select></Field></>}
    {type==="journal"&&<><div className={styles.formGrid}><Field label="日志类型"><select value={form.entryType} onChange={e=>update("entryType",e.target.value)}><option value="observation">观察</option><option value="judgement">判断变更</option><option value="review">复盘</option></select></Field><Field label="日期"><input type="date" value={form.date} onChange={e=>update("date",e.target.value)}/></Field></div><Field label="标题"><input required value={form.title||""} onChange={e=>update("title",e.target.value)}/></Field><Field label="内容"><textarea required rows="5" value={form.body||""} onChange={e=>update("body",e.target.value)}/></Field><div className={styles.formGrid}><Field label="变更前置信度"><input type="number" min="0" max="100" value={form.confidenceBefore} onChange={e=>update("confidenceBefore",Number(e.target.value))}/></Field><Field label="变更后置信度"><input type="number" min="0" max="100" value={form.confidenceAfter} onChange={e=>update("confidenceAfter",Number(e.target.value))}/></Field></div></>}
    {type==="action"&&<><div className={styles.formGrid}><Field label="行动"><select value={form.actionType} onChange={e=>update("actionType",e.target.value)}><option value="watch">观察</option><option value="initiate">建仓</option><option value="add">加仓</option><option value="reduce">减仓</option><option value="exit">退出</option></select></Field><Field label="日期"><input type="date" value={form.date} onChange={e=>update("date",e.target.value)}/></Field></div><div className={styles.formGrid}><Field label="仓位 %"><input type="number" step="any" value={form.positionSize} onChange={e=>update("positionSize",Number(e.target.value))}/></Field><Field label="价格（可选）"><input type="number" step="any" value={form.price||""} onChange={e=>update("price",Number(e.target.value))}/></Field></div><Field label="行动依据"><textarea required rows="4" value={form.reason||""} onChange={e=>update("reason",e.target.value)}/></Field></>}
    <div className={styles.modalActions}><button type="button" onClick={onClose}>取消</button><button className={styles.primaryButton}>保存记录</button></div>
  </form></Modal>;
}
