import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
const temp = path.join(os.tmpdir(), `research-store-${process.pid}.json`);
process.env.RESEARCH_DATA_PATH = temp;
const store = await import("../src/lib/researchStore.js");
assert.deepEqual(Object.keys(store.emptyStore()), store.ENTITY_KEYS);
const asset = store.createEntity("assets", { symbol: "TEST", name: "Test Asset", stage: "story" });
const evidence = store.createEntity("evidence", { assetId: asset.id, chainStage: "usage", sourceName: "Test source" });
assert.equal(store.assetBundle(asset.id).evidence[0].id, evidence.id);
const updated = store.updateEntity("assets", asset.id, { stage: "evidence" });
assert.equal(updated.stage, "evidence");
assert.ok(updated.updatedAt);
assert.equal(store.deleteEntity("assets", asset.id), true);
assert.equal(store.readStore().evidence.length, 0);
fs.rmSync(temp, { force: true });
console.log("researchStore CRUD, bundle and cascade delete: PASS");
